### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by FutureSharks** [stefanpf/jobsiteScrape.py#9]
I get this error ever now although first run worked OK:

```
$ rm -f runlog.txt *.xlsx
$ python jobsiteScrape.py
/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
runlog.txt not found.
How many days back should I start scraping?
2
Scraping berlinstartupjobs.com/operations/ for links...
Finished scraping berlinstartupjobs.com/operations/
Writing results to spreadsheet...
Workbook not found, creating a new workbook...
New workbook created.
Workbook opened.
Workbook saved and closed.
Scraping berlinstartupjobs.com/engineering/ for links...
Finished scraping berlinstartupjobs.com/engineering/
Writing results to spreadsheet...
Workbook opened.
Workbook saved and closed.
Scraping stepstone.de for links...
Traceback (most recent call last):
  File "jobsiteScrape.py", line 250, in <module>
    scrape_stepstone(stepstone_search_string)
  File "jobsiteScrape.py", line 115, in scrape_stepstone
    job_desc = soup.select('.offer__section')[0].getText()
IndexError: list index out of range
```

**Comment by stefanpf** [comment]
Yeah, I opened an issue for this just before you did. See there for what I tried already.

**Comment by ronoz** [comment]
hi stefan great work, can you get back to me please?

**Comment by stefanpf** [comment]
Sure. Can you tell me who you are?
